# Generated by Django 5.0.4 on 2024-04-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10)),
                ('case_name', models.TextField()),
                ('triggered_by', models.CharField(max_length=100)),
                ('test_result', models.CharField(max_length=10)),
                ('log_link', models.URLField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
