name: Get Latest Item

on:
  schedule:
    - cron: '0 * * * *'  # 每小时触发一次

jobs:
  fetch_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 更新到 v3

      - name: Set up Python
        uses: actions/setup-python@v4  # 更新到 v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Cache last_content.json
        uses: actions/cache@v3  # 保持使用 v3
        with:
          path: last_content.json
          key: ${{ runner.os }}-last-content

      - name: Run script
        run: python Actions/get_latest_item_for_GET.py

      - name: Save last_content.json
        run: |
          if [ -f last_content.json ]; then
            # Check if the target file already exists
            if [ -f ${{ github.workspace }}/last_content.json ]; then
              # Remove the target file if it exists
              rm ${{ github.workspace }}/last_content.json
            fi
            # Move the file
            mv last_content.json ${{ github.workspace }}/last_content.json
            echo "last_content.json saved."
          else
            echo "last_content.json does not exist, skipping save."
          fi
