# .github/workflows/main.yml
name: Get Latest Item

on:
  schedule:
    - cron: '5 * * * *'   # 每小时5分触发
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pytz

      - name: Run script
        run: |
          python Actions/get_latest_item_for_GET.py

      - name: Check if previous result file exists
        run: |
          if [ -f previous_result.json ]; then
            if [ -s previous_result.json ]; then
              echo "File exists and is not empty."
            else
              echo "File exists but is empty."
              exit 1  # 退出并标记为失败
            fi
          else
            echo "File does not exist."
            exit 1  # 退出并标记为失败
          fi

      - name: Commit and push previous result
        run: |
          git config --local user.name "jerryblues"
          git config --local user.email "jerry_0a@163.com"
          git add previous_result.json
          # 检查是否有更改
          if ! git diff --cached --quiet; then
            git commit -m "Update previous result file"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token
