# .github/workflows/main.yml
name: get_info

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '5 * * * *'      # get_latest_item 每小时5分触发
    - cron: '0 5,14 * * *'   # get_stock_info 每日13:00,22:00触发

jobs:
  get_latest_item:
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '5 * * * *' # 手动或定时触发
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pytz

      - name: Run script
        run: |
          python Actions/get_latest_item_for_GET.py

      - name: Check if previous result file exists
        run: |
          if [ -f previous_result.json ]; then
            if [ -s previous_result.json ]; then
              echo "File exists and is not empty."
            else
              echo "File exists but is empty."
              exit 1  # 退出并标记为失败
            fi
          else
            echo "File does not exist."
            exit 1  # 退出并标记为失败
          fi

      - name: Commit and push previous result
        run: |
          git config --local user.name "jerryblues"
          git config --local user.email "jerry_0a@163.com"
          git add previous_result.json
          # 检查是否有更改
          if ! git diff --cached --quiet; then
            git commit -m "Update previous result file"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token

  get_stock_info:
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 5,14 * * *'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests yfinance

      - name: Run script
        run: |
          python Actions/get_stock_info.py
