# Generated by Django 5.0.4 on 2024-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testcase_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='case_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='log_link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_result',
            field=models.CharField(max_length=100),
        ),
    ]
