# Generated by Django 5.0.4 on 2024-04-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_testcase_case_name_alter_testcase_log_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
